services:
  api-server:
    build: api
    image: webinar-api
    container_name: webinar-api
    ports:
      - "8080:8080"
    depends_on:
      - webinar-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  webinar-db:
    image: postgres:16.1
